TeamPhotoSurfer/PhotoSurfer-iOS

PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A10.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A30.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A70.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaOceanA60.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaOceanA75.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA10.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA30.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA70.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayBlack.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray10.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray20.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray30.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray40.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray5.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray50.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray60.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray70.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray80.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray90.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray950.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayWhite.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointBlue.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointGreen.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointMain.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointRed.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointSub.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointYellow.colorset/Contents.json, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIColor+.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIFont+.swift
closed #8 
컬러와 폰트 익스텐션을 추가했습니다
=> [#8] 컬러 및 폰트 에셋 추가

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift
=> [#7] 홈 에셋 제외한 UI

PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearch.storyboard
closed #13 
일단 전체적인 부분을 추가했고
태그하나의 크기, 헤더는 퇴근하고 와서 추가할게욤
=> [#13] 검색뷰 서치바 및 컬렉션뷰 추가

PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Base.lproj/MainInterface.storyboard, PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.xib, PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.swift, PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.xib, PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/AppDelegate.swift
closed #16 
share extension 태그 검색 diffable data source 구현
=> [#16] share extension 태그 검색 기능 구현

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Image.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
=> [#35] 검색결과 UI

PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetAlarmViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController+Extension.swift
=> [#57] 대표 태그, 알림 설정 기능 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
=> [#70] tag type

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearch.storyboard
=> [#72] view detail hs

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
closed #86 
https://user-images.githubusercontent.com/63438947/179821306-06fb454c-f247-4f38-8895-fd0a944b5d03.MP4
=> [#86] 태그 검색 뷰 디테일 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkConstant.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/URLConstant.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
=> [#91] get push server hs

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/TagModel/TagResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkConstant.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/TagAPI/TagRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/TagAPI/TagService.swift
=> [#94] 홈 자주 검색한 태그 연결

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
=> [#97] 태그 중복 제어, 디자인 오류 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
=> [#99] 태그수정 UI detail

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
=> [#101] /tag/main

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PhotoModel/PhotoResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift
=> [#106] 검색결과 서버연결

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
=> [#116] todayAPI 연결

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
=> [#120] 검색 태그 삭제시 새로고침

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Controllers/AlarmDetailViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Views/AlarmDetail.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
=> [#122] 알림상세 이동시 id값 전달

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagDetailViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
closed #125 
태그 앨범 상세 API를 붙였습니다.
=> [#125] get tag detail

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Views/SetAlarm.storyboard, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
=> [#104] 사진에 태그 추가  - post ~/photo

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
=> [#127] detail hs

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Controllers/AlarmDetailViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Views/AlarmDetail.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
=> [#133] 알림 상세

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
closed #132 
태그 즐겨찾기 API를 연결했습니다.
즐겨찾기 등록 이후 태그 get 통신을 하여 결과를 띄워주도록 했습니다.
=> [#132] 태그 북마크 추가 API

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
=> [#136] 검색 로직 오류 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
closed #138 
태그탭의 북마크 삭제 API를 연결했습니다.
=> [#138] Del tag mark

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
closed #140 
태그탭에서 태그 앨범 삭제 API를 연결했습니다.
=> [#140] 태그 삭제 API 연결

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagDetailViewController.swift
closed #144 
태그 앨범 사진 상세 API를 연결했습니다
=> [#144] 태그 앨범 사진 상세 API 연결

PhotoSurfer-iOS/ImageShareExtension/Source/Extensions/UIViewController+.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
=> [#130] post - push/:photoid 알림설정 서버 연결

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift
closed #146 
empty view에서 온보딩 표시후 로그인 화면으로 돌아가는 오류에 대한 분기처리를 했습니다.
=> [#146] 온보딩 분기처리 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PhotoModel/PhotoResponse.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
=> [#127] 사진에 태그 추가

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
=> [#153] 태그탭 레이아웃 수정

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
=> [#150] 검색 뷰 오류 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
=> [#127] 개별사진 태그수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
=> [#45] 검색결과 다중선택

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
=> [#159] multiselect tag UI

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
=> [#153] 태그탭 UI 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
=> [#159] 다중사진 태그삭제

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Views/SetAlarm.storyboard, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
=> [#160] 뷰 에러 수정 및 키보드 로직 변경

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
=> [#159] 다중선택 태그추가

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
=> [#159] 다중선택 수정

PhotoSurfer-iOS/ImageShareExtension/Source/Extensions/UIViewController+.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
=> [#179] layout 에러 수정

PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift, PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
=> [#179] 저장 안되는 오류 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Controllers/SettingUserViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
=> [#182] 자잘한 코드 정리

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/AppDelegate.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Views/AlarmList.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift
=> [#174] 뒤로가기, 선택 색상 수정

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
=> [#174] 태그검색 엠티뷰 추가

PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard, PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
=> [X] 태그앨범 다중선택 추가
